plugins {
    id 'com.android.application'
}

android {
    namespace 'com.fixfinans.app'
    compileSdk 35

    defaultConfig {
        applicationId 'com.fixfinans.app'
        minSdk 23
        targetSdk 35
        versionCode 1317
        versionName '13.1.7'
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}
